languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "老冯云数"

[params]
displayName = "简体中文"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006-01-02"
logo = "img/logo.png"
description = "老冯云数，数据库老司机，云计算泥石流，PGSQL大法师"
copyright = "© 2025 冯若航"

[params.author]
  name = "冯若航"
  email = "rh@vonng.com"
  image = "img/vonng.jpg"
  imageQuality = 96
  headline = "Pigsty 创始人, @Vonng"
  bio = "Pigsty 创始人, @Vonng"
  links = [
    { email = "mailto:rh@vonng.com" },
    { link = "https://vonng.com/" },
    { github = "https://github.com/Vonng" },
    { linkedin = "https://www.linkedin.com/in/vonng/" },
    { medium = "https://medium.com/@fengruohang/"  },
    { discord = "https://discord.gg/j5pG8qfKxU" },
    { telegram = "https://t.me/joinchat/gV9zfZraNPM3YjFh" }
  ]
