# .github/workflows/deploy.yml
name: Deploy Hugo site to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read      # 允许读取源码
  pages: write        # 允许写 Pages
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码 & 子模块
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # 2. 缓存 Hugo Modules & resources/ 目录
      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo          # 模块缓存
            resources              # 图片等中间结果
          key: hugo-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            hugo-${{ runner.os }}-${{ github.ref }}
            hugo-${{ runner.os }}

      # 3. 安装 Go（Blowfish 某些短码需用到）
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      # 4. 安装 Hugo extended 0.148.2
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.148.2"
          extended: true

      # 5. 配置 Pages 变量（用于 baseURL）
      - id: pages
        uses: actions/configure-pages@v4

      # 6. 构建
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      # 7. 上传构建产物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 将上一步产物发布到 GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
